site_name: Risk Data Center Documentation
site_description: Documentation for the Risk Data Center system and its database structure
site_author: Your Team Name

# Repository
repo_name: risk_datacenter_readme
repo_url: # Add your repository URL if applicable

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: indigo
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html

# Navigation structure
nav:
  - Home: index.md
  - Database:
      - PostgreSQL: database.md
      - MongoDB: mongodb.md
  - Handbook: handbook.md
  - Schedule: schedule.md
  # You can add more sections as they're created
  # - API Reference: api.md
  # - User Guide: user-guide.md
  # - Developer Guide: developer-guide.md

# Plugins
plugins:
  - search
  - mermaid2

# Extra configuration
extra:
  social:
    # Add your social links if needed
    # - icon: fontawesome/brands/github
    #   link: https://github.com/yourusername
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="..." target="_blank" rel="noopener">telling us what you're missing</a>.